### ISSUE TITLE
Use Secrets Manager instead of Parameter Store for username/password

### ISSUE THREAD

**Issue by ramgrandhi** [ramgrandhi/serverless-wso2-apim#73]
Currently, `wso2apim.user` and `wso2apim.pass` support either 'hardcoded' or Serverless parameter syntax (which includes ${ssm:/...), however, it only can grab values from `AWS Systems Manager -> Parameter Store`.

However, some teams might want to preserve credentials in `AWS Secrets Manager` as a secret and the plug-in shall source its values and use it for execution. Use AWS Managed Keys here, for general use.

NOTE: AWS SDK code sample to retrieve secret values from AWS Secrets Manager. : https://docs.aws.amazon.com/code-samples/latest/catalog/javascript-secrets-secrets_getsecretvalue.js.html

**Comment by ckuijjer** [comment]
It seems possible to get access to the AWS Secrets Manager secrets using the `${ssm:/...}` syntax, by prefixing it with `/aws/reference/secretsmanager/`.

For example for the secrets _oh-so-secret_, you can use `${ssm:/aws/reference/secretsmanager/oh-so-secret}`

**Comment by ramgrandhi** [comment]
Thanks @ckuijjer for the tip!
