### ISSUE TITLE
Plugin does not publish swagger spec

### ISSUE THREAD

**Issue by crunchie84** [ramgrandhi/serverless-wso2-apim#80]
After API definition is created/updated in WSO2 the swagger spec is not published. This results in the API store only rendering the endpoints + method without any of the additional swagger information available/created by the API owner (engineers)

In terms of pre-work I already did some investigation:

- In function `createAPIDef` the POST /apis data endpoint will return the whole api definition including its id
- It seems that this `id` can be used to PUT the swagger spec (https://apim.docs.wso2.com/en/3.2.0/develop/product-apis/publisher-apis/publisher-v1/publisher-v1/#tag/APIs/paths/~1apis~1{apiId}~1swagger/put)
- It feels logical to have this happen before invoking the `publishAPIDef` function which transitions the api lifecycle

**Comment by ramgrandhi** [comment]
Sorry for the delay, Thanks for your contribution!

I'm on closing your PR, @crunchie84. Keep you posted.
