### ISSUE TITLE
Add support for Restricted (role based) Developer portal visibility and Publisher Access control

### ISSUE THREAD

**Issue by gustaafj** [ramgrandhi/serverless-wso2-apim#91]
Currently, the plugin allows for Developer Portal Visibility options: PUBLIC and PRIVATE and no options for Publisher Portal Access. 
 
The desired behavior would be that it (also) allows for Developer Portal Visibility and Publisher Access Control that is Restricted by Roles and that you can specify the roles that are authorized to access the api in the developer and publisher portals.

**Comment by ramgrandhi** [comment]
Thank you for reporting the issue @gustaafj! Could you (perhaps) look around the source and propose potential changes here?

**Comment by gustaafj** [comment]
Hi @ramgrandhi , I'll give it a try!

**Comment by ramgrandhi** [comment]
@gustaafj - Closing this issue as this feature has been released under [0.6.1-alpha.1](https://github.com/ramgrandhi/serverless-wso2-apim/releases/tag/0.6.1-alpha.1)
